# Generated by Django 6.0.1 on 2026-02-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='admin_response',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='response_date',
        ),
        migrations.AddField(
            model_name='feedback',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cevaplanma Tarihi'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Cevabı'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram Kullanıcı Adı'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='series',
            name='type',
            field=models.CharField(choices=[('manga', 'Manga (Japon)'), ('webtoon', 'Webtoon (Dikey)'), ('manhwa', 'Manhwa (Kore)'), ('manhua', 'Manhua (Çin)')], default='webtoon', max_length=10),
        ),
    ]
