# Generated by Django 6.0.2 on 2026-02-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_remove_feedback_admin_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='status',
            field=models.CharField(choices=[('devam', '🟢 Devam Ediyor'), ('tamamlandi', '🔴 Final Yaptı (Tamamlandı)'), ('ara', '⏸️ Ara Verildi (Sezon Finali)')], default='devam', max_length=15, verbose_name='Seri Durumu'),
        ),
    ]
