# Generated by Django 6.0.2 on 2026-03-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_spoiler',
            field=models.BooleanField(default=False, verbose_name='Spoiler İçeriyor'),
        ),
    ]
