# Generated by Django 6.0.2 on 2026-03-26 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_comment_is_spoiler'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_series', to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen Kişi'),
        ),
    ]
